# Generated by Django 4.2.11 on 2024-04-19 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_comment_challenge_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
